### ISSUE TITLE
Residual particle effect from old, destroyed gates

### ISSUE THREAD

**Issue by minisat0shi** [Jarada/WuufusWaygates#15] opened 2023-09-03 16:10 UTC
When destroying a gate with the magic effect, the magic effect remains. Seemingly no way to remove it without deleting all gates from the world (which requires much work to rebuild all functioning gates). Not sure if there is an easy fix I am missing or if there just needs to be a way to delete old/residual gates?

Thanks!

**Comment by minisat0shi** [comment] 2023-09-03 16:25
Correction: the more a gate is used the stronger the effect gets. Not lingering old gates.

**Comment by minisat0shi** [comment] 2023-09-03 16:30
Even after changing to water gates, restarting server, the magic effect lingers, and progressively gets worse with each teleport.

**Comment by minisat0shi** [comment] 2023-09-03 18:07
Only fix was to set particles to none inside the config

**Comment by Jarada** [comment] 2023-09-03 21:03
Thanks for raising this issue. I'll look at this during this week, alongside an upcoming new feature release.

**Comment by minisat0shi** [comment] 2023-09-03 21:05
Sweet, thanks!

**Comment by Jarada** [comment] 2023-09-12 21:34
Hi there, thanks for your patience on this. I'm not able to reproduce this on the latest 1.20.1 using Paper.

Are you able to confirm the following:
- What version of Minecraft does this occur on?
- What version of the server are you using; Spigot, Paper, or some other fork?
- That the magic effect gets stronger when you teleport? Are you able to post a screenshot of this?

Thanks for your assistance on it!

**Comment by Jarada** [comment] 2023-11-08 16:22
Closed as unable to reproduce. Feel free to reopen if this issue reoccurs.

**Closed** 2023-11-08 16:23 UTC
Labels: bug
